# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTy3d():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_ty3d(self):
    self.driver.get("https://my.simulation.cloud/login?ref=https://tidy3d.simulation.cloud/")
    self.driver.set_window_size(1704, 967)
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("gehui19_1734358944@snapmail.cc")
    self.driver.find_element(By.CSS_SELECTOR, ".ant-input-affix-wrapper").click()
    self.driver.find_element(By.ID, "password").send_keys("1983#GEhui")
    self.driver.find_element(By.ID, "sign-in-with-email").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".anticon-fc\\3Atidy3d-collapse_outline > svg")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".anticon-fc\\3Atidy3d-collapse_outline > svg").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".side-item-selected .side-text").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "#nz-tabs-0-tab-1 > .fc-header-container")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-star-inserted:nth-child(5) .card-img").click()
    self.driver.find_element(By.CSS_SELECTOR, ".run-text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".pass-color").click()
    self.driver.find_element(By.CSS_SELECTOR, ".pass-color").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".pass-color")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".pass-color").click()
    self.driver.find_element(By.CSS_SELECTOR, ".run-text").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".panel_footer > .ant-btn:nth-child(2) > .ng-star-inserted").click()
    self.driver.find_element(By.CSS_SELECTOR, ".download .ng-star-inserted").click()
    self.driver.find_element(By.CSS_SELECTOR, ".files-download:nth-child(1)").click()
  
