# Generated by Selenium IDE
import time

import pytest

# def test_td(chrome_options):
#     # Test name: td
#     # Step # | name | target | value
#     # 1 | open | / |
#     chrome_options.get("https://www.baidu.com/")
#     # 2 | setWindowSize | 1704x967 |
#     chrome_options.set_window_size(1704, 967)
#     # 3 | type | id=kw | china
#     chrome_options.find_element(By.ID, "kw").send_keys("china ")
#     # 4 | click | id=su |
#     chrome_options.find_element(By.ID, "su").click()
from tests.step_defs.baidu_search import LoginObject


class TestTd:
    def setup(self):

        print("setup_method")

    def teardown(self):
        print("teardown_method")

    def test_td(self, chrome_browser):
        # Test name: td
        # Step # | name | target | value
        # 1 | open | / |
        chrome_browser.get("https://www.baidu.com/")
        login_object = LoginObject(chrome_browser)

        # 2 | type | id=kw | china
        login_object.search_input().send_keys('china')

        # 3 | click | id=su |
        login_object.search_button().click()
        pytest.assume(True, "False")
        # assert True, login_object.validate()

        chrome_browser.save_screenshot("baidu-" + str(int(time.time())) + "-01.png")
        # flag = login_object.validate()
        pytest.assume(True, "True")
        print("pytest.assume(True, 'True')")

