# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestUntitled():
    def setup_method(self, method):
        pass

    def teardown_method(self, method):
        pass

    def test_untitled(self, chrome_browser):
        chrome_browser.get("https://pic.sogou.com/")
        chrome_browser.set_window_size(1704, 967)
        chrome_browser.find_element(By.XPATH, "//a[@id=\'cameraIco\']/i").click()
        # chrome_browser.find_element(By.CSS_SELECTOR, "input:nth-child(2)").click()
        time.sleep(3)
        chrome_browser.find_element(By.CSS_SELECTOR, "input:nth-child(2)").send_keys("/home/james/Downloads/001.jpeg")
        time.sleep(2)
        chrome_browser.save_screenshot("sugou.png")
        chrome_browser.find_element(By.XPATH, '//*[@id="headsearch"]/div/form/div/input[1]')
        time.sleep(2)
        chrome_browser.save_screenshot("sugou-001.png")

    def test_dowload_file(self, chrome_browser):
        chrome_browser.get(
            "https://pic.sogou.com/d?len=10&start=2&did=5&category_from=recommend&query=%E7%BB%84%E5%9B%BE%3A%E5%88%98%E9%9B%AF%E8%83%B6%E7%89%87%E8%B4%A8%E6%84%9F%E5%A4%A7%E7%89%87%E6%9B%9D%E5%85%89%20%E5%BE%AE%E9%86%BA%E7%81%AF%E5%85%89%E4%B8%8B%E5%B1%95%E7%8E%B0%E5%A5%B3%E6%80%A7%E4%BC%98%E9%9B%85%E8%87%AA%E5%A6%82%E7%9A%84%E5%8A%9B%E9%87%8F&groupDid=1&actionType=next&channel=pc_pic&scene=pic_result")

        time.sleep(2)
        e = chrome_browser.find_element(By.XPATH, '//*[@id="foot"]/div[1]/div[2]/a')
        e.click()
        print(chrome_browser.title)
        # chrome_browser.refresh()

        time.sleep(25)
        # chrome_browser.download_file("/tmp/组图_刘雯胶片质感大片曝光\ 微醺灯光下展现女性优雅自如的力量.jpg", "./")

        chrome_browser.save_screenshot("do.png")
